import { spawn } from "node:child_process";
import { playlistPath, sdpPath, segmentPath } from "./config";

export function spawnHlsFfmpeg() {
  return spawn("ffmpeg", [
    "-protocol_whitelist",
    "file,rtp,udp",
    "-fflags",
    "+genpts",
    "-analyzeduration",
    "5M",
    "-probesize",
    "5M",
    "-i",
    sdpPath,
    "-map",
    "0:v:0",
    "-c:v",
    "libx264",
    "-preset",
    "veryfast",
    "-tune",
    "zerolatency",
    "-pix_fmt",
    "yuv420p",
    "-map",
    "0:a:0",
    "-c:a",
    "aac",
    "-b:a",
    "128k",
    "-ar",
    "48000",
    "-f",
    "hls",
    "-hls_time",
    "1",
    "-hls_list_size",
    "6",
    "-hls_flags",
    "delete_segments+append_list+omit_endlist",
    "-hls_segment_filename",
    segmentPath,
    playlistPath,
  ]);
}
